LongName: New Mexico State University Discovery Cluster
Description: Slurm HPC system at New Mexico State

ID: 10239

AddressLine1: 1780 E University Ave
City: Las Cruces

Country: USA
State: New Mexico
Zipcode: "88003"

Latitude: 32.278267
Longitude: -106.747541

